import React, {ReactNode} from 'react';
import {ActivityIndicator, Pressable, StyleSheet, Text as RNText, TextInput as RNTextInput, TextInputProps, View} from 'react-native';
import {useTheme} from '@app/providers/AppProviders';

export function Text({children, variant = 'body', color, testID}: {children: ReactNode; variant?: 'caption' | 'body' | 'title' | 'display'; color?: string; testID?: string}) {const t = useTheme(); return <RNText testID={testID} allowFontScaling style={[styles.text, {fontSize: t.typography[variant], color: color ?? t.colors.text}, variant === 'title' || variant === 'display' ? styles.strong : undefined]}>{children}</RNText>;}
export function Button({title, onPress, disabled, loading, variant = 'primary', testID, accessibilityLabel}: {title: string; onPress: () => void; disabled?: boolean; loading?: boolean; variant?: 'primary' | 'secondary' | 'danger'; testID?: string; accessibilityLabel?: string}) {const t = useTheme(); const backgroundColor = variant === 'primary' ? t.colors.primary : variant === 'danger' ? t.colors.danger : t.colors.surface; const color = variant === 'secondary' ? t.colors.text : t.colors.onPrimary; return <Pressable accessibilityRole="button" accessibilityLabel={accessibilityLabel ?? title} testID={testID} disabled={disabled || loading} onPress={onPress} style={({pressed}) => [styles.button, {backgroundColor, borderColor: t.colors.border, opacity: disabled ? 0.5 : pressed ? 0.8 : 1}]}>{loading ? <ActivityIndicator color={color}/> : <Text color={color}>{title}</Text>}</Pressable>;}
export function TextInput({label, error, testID, ...props}: TextInputProps & {label: string; error?: string; testID?: string}) {const t = useTheme(); return <View style={styles.field}><Text variant="caption">{label}</Text><RNTextInput accessibilityLabel={label} testID={testID} placeholderTextColor={t.colors.muted} style={[styles.input, {color: t.colors.text, borderColor: error ? t.colors.danger : t.colors.border, backgroundColor: t.colors.surface}]} {...props}/>{error ? <Text variant="caption" color={t.colors.danger}>{error}</Text> : null}</View>;}
export function PasswordInput(props: React.ComponentProps<typeof TextInput>) {return <TextInput secureTextEntry autoCapitalize="none" textContentType="password" {...props}/>;}
export function Checkbox({checked, label, onChange, testID}: {checked: boolean; label: string; onChange: (value: boolean) => void; testID?: string}) {const t = useTheme(); return <Pressable accessibilityRole="checkbox" accessibilityState={{checked}} testID={testID} onPress={() => onChange(!checked)} style={styles.row}><View style={[styles.checkbox, {borderColor: t.colors.primary, backgroundColor: checked ? t.colors.primary : 'transparent'}]}>{checked ? <Text color={t.colors.onPrimary}>✓</Text> : null}</View><Text>{label}</Text></Pressable>;}
export function Badge({label, tone = 'neutral'}: {label: string; tone?: 'neutral' | 'success' | 'warning'}) {const t = useTheme(); const color = tone === 'success' ? t.colors.success : tone === 'warning' ? t.colors.warning : t.colors.muted; return <View style={[styles.badge, {borderColor: color}]}><Text variant="caption" color={color}>{label}</Text></View>;}
export function Avatar({name}: {name: string}) {const t = useTheme(); const initials = name.split(' ').map(part => part[0]).slice(0, 2).join(''); return <View accessibilityLabel={`${name} avatar`} style={[styles.avatar, {backgroundColor: t.colors.primary}]}><Text color={t.colors.onPrimary}>{initials}</Text></View>;}
export function Divider() {const t = useTheme(); return <View style={[styles.divider, {backgroundColor: t.colors.border}]}/>;}
export function LoadingIndicator({label = 'Loading'}: {label?: string}) {const t = useTheme(); return <View accessibilityLabel={label} style={styles.center}><ActivityIndicator color={t.colors.primary}/></View>;}
const styles = StyleSheet.create({text: {fontWeight: '400'}, strong: {fontWeight: '700'}, button: {minHeight: 48, borderRadius: 12, borderWidth: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16}, field: {gap: 6}, input: {minHeight: 48, borderWidth: 1, borderRadius: 10, paddingHorizontal: 12, fontSize: 16}, row: {flexDirection: 'row', alignItems: 'center', gap: 8}, checkbox: {height: 24, width: 24, borderWidth: 2, borderRadius: 5, alignItems: 'center', justifyContent: 'center'}, badge: {borderWidth: 1, borderRadius: 999, paddingHorizontal: 9, paddingVertical: 3}, avatar: {height: 42, width: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center'}, divider: {height: StyleSheet.hairlineWidth}, center: {padding: 24, alignItems: 'center'}});
