import React, {PropsWithChildren} from 'react';
import {Modal, Pressable, StyleSheet, View} from 'react-native';
import {useTheme} from '@app/providers/AppProviders';
import {Button, Text} from '@components/atoms';
export function Card({children, testID}: PropsWithChildren<{testID?: string}>) {const t = useTheme(); return <View testID={testID} style={[styles.card, {backgroundColor: t.colors.surface, borderColor: t.colors.border}, t.shadow]}>{children}</View>;}
export function EmptyState({title, message, action}: {title: string; message: string; action?: {label: string; onPress: () => void}}) {return <View style={styles.state}><Text variant="title">{title}</Text><Text>{message}</Text>{action ? <Button title={action.label} onPress={action.onPress}/> : null}</View>;}
export function ErrorState({message, onRetry}: {message: string; onRetry?: () => void}) {return <EmptyState title="Something went wrong" message={message} action={onRetry ? {label: 'Try again', onPress: onRetry} : undefined}/>;}
export function ConfirmationDialog({visible, title, message, onConfirm, onCancel}: {visible: boolean; title: string; message: string; onConfirm: () => void; onCancel: () => void}) {const t = useTheme(); return <Modal transparent visible={visible} animationType="fade" onRequestClose={onCancel}><View style={[styles.overlay, {backgroundColor: t.colors.overlay}]}><Card><Text variant="title">{title}</Text><Text>{message}</Text><View style={styles.actions}><Button title="Cancel" variant="secondary" onPress={onCancel}/><Button title="Confirm" variant="danger" onPress={onConfirm}/></View></Card></View></Modal>;}
export function SkeletonLoader() {const t = useTheme(); return <View accessibilityLabel="Loading content" style={[styles.skeleton, {backgroundColor: t.colors.border}]}/>;}
export function BottomSheet({visible, onClose, children}: PropsWithChildren<{visible: boolean; onClose: () => void}>) {const t = useTheme(); return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><Pressable style={[styles.sheetOverlay, {backgroundColor: t.colors.overlay}]} onPress={onClose}/><View style={[styles.sheet, {backgroundColor: t.colors.surface}]}>{children}</View></Modal>;}
const styles = StyleSheet.create({card: {borderWidth: 1, borderRadius: 12, padding: 16, gap: 12}, state: {flex: 1, justifyContent: 'center', alignItems: 'center', gap: 12, padding: 24}, overlay: {flex: 1, justifyContent: 'center', padding: 24}, actions: {flexDirection: 'row', justifyContent: 'flex-end', gap: 8}, skeleton: {height: 84, borderRadius: 12, opacity: 0.55}, sheetOverlay: {flex: 1}, sheet: {padding: 24, minHeight: 180, borderTopLeftRadius: 20, borderTopRightRadius: 20},});
